#!/bin/bash

if [[ "$1" = "" || "$2" = "" ]] ; then
	echo "Usage: z-build <gplaynormal|gplayhardcore|fdroidnormal|fdroidhardcore> <debug|release> [install]"
	exit
fi

if [[ "$3" = "install" ]] ; then
	PREFIX="install"
else
	PREFIX="assemble"
fi

case "$2" in
	debug)
		SUFFIX="Debug"
		;;

	release)
		SUFFIX="Release"
		;;

	*)
		echo "Unknown build type: $2"
		exit
esac

case "$1" in
	gplaynormal)
		TASK="GplaynormalNormalWithanalyticsWithzeemoteWithrateoffer"
		;;

	gplayhardcore)
		TASK="GplayhardcoreHardcoreWithanalyticsWithzeemoteWithrateoffer"
		;;

	fdroidnormal)
		TASK="FdroidnormalNormalWithoutanalyticsWithoutzeemoteWithoutrateoffer"
		;;

	fdroidhardcore)
		TASK="FdroidhardcoreHardcoreWithoutanalyticsWithoutzeemoteWithoutrateoffer"
		;;

	*)
		echo "Unknown build variant: $1"
		exit
esac

./gradlew "${PREFIX}${TASK}${SUFFIX}"
