#!/bin/bash

if [[ "$1" = "" || "$2" = "" ]] ; then
	echo "Usage: z-build <gplaynormal|gplayhardcore|fdroidnormal|fdroidhardcore> <debug|release> [install]"
	exit
fi

VERSION_NAME=`cat gradle.properties | grep VERSION_NAME | sed -e 's/^[ ]*VERSION_NAME[ ]*=//' | sed -e 's/[ ]*$//'`

if [[ "$3" = "install" ]] ; then
	PREFIX="install"
else
	PREFIX="assemble"
fi

case "$2" in
	debug)
		SUFFIX="Debug"
		;;

	release)
		SUFFIX="Release"
		;;

	*)
		echo "Unknown build type: $2"
		exit
esac

case "$1" in
	gplaynormal)
		TASK="GplaynormalNormalWithanalyticsWithzeemoteWithrateoffer"
		SRCNAME="gloomy-dungeons-1-gplaynormal-normal-withanalytics-withzeemote-withrateoffer-release.apk"
		DSTNAME="gloomy-dungeons-1-gplaynormal-${VERSION_NAME}.apk"
		;;

	gplayhardcore)
		TASK="GplayhardcoreHardcoreWithanalyticsWithzeemoteWithrateoffer"
		SRCNAME="gloomy-dungeons-1-gplayhardcore-hardcore-withanalytics-withzeemote-withrateoffer-release.apk"
		DSTNAME="gloomy-dungeons-1-gplayhardcore-${VERSION_NAME}.apk"
		;;

	fdroidnormal)
		TASK="FdroidnormalNormalWithoutanalyticsWithoutzeemoteWithoutrateoffer"
		;;

	fdroidhardcore)
		TASK="FdroidhardcoreHardcoreWithoutanalyticsWithoutzeemoteWithoutrateoffer"
		;;

	*)
		echo "Unknown build variant: $1"
		exit
esac

./gradlew "${PREFIX}${TASK}${SUFFIX}"

if [[ "$2" = "release" && -e "temp" && "$SRCNAME" != "" && "$DSTNAME" != "" ]] ; then
	[ -e "temp/${DSTNAME}" ] && rm "temp/${DSTNAME}"
	[ -e "build/outputs/apk/${SRCNAME}" ] && cp "build/outputs/apk/${SRCNAME}" "temp/${DSTNAME}"
fi
